# ~/.config/starship.toml

add_newline = false

# A minimal left prompt
format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$shell"""

[shell]
zsh_indicator = '❯'
powershell_indicator = '_'
unknown_indicator = '❓ '
style = 'green bold'
disabled = false

[directory]
style = "cyan bold"
truncation_length = 3
truncate_to_repo = true
read_only = " "

[git_branch]
symbol = " "
style = "yellow bold"
format = "[$symbol$branch]($style) "

[git_status]
format = "([$staged$modified$deleted]($style))"

staged = "[+${count}](green) "
modified = "[~${count}](#FFA500) "
deleted = "[-${count}](red) "

style = "white"


[cmd_duration]
min_time = 500
format = "took [$duration]($style) "
style = "yellow"
