# ~/.config/starship.toml

add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$dotnet\
$java\
$nodejs\
$cmd_duration\
$line_break\
$character
"""

# --------------------
# Directory
# --------------------
[directory]
style = "cyan bold"
truncation_length = 3
truncate_to_repo = true
read_only = " "

# --------------------
# Git (only shows inside repos automatically)
# --------------------
[git_branch]
symbol = " "
style = "purple bold"

[git_status]
style = "purple"
format = "([$all_status$ahead_behind]($style)) "
conflicted = "⚔ "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
modified = " "
staged = " "
renamed = "󰑕 "
untracked = " "
deleted = "󰆴 "

# --------------------
# .NET
# --------------------
[dotnet]
symbol = "󰪮 "
style = "blue bold"
format = "[$symbol($version )]($style)"

# --------------------
# Java
# --------------------
[java]
symbol = " "
style = "red bold"
format = "[$symbol($version )]($style)"

# --------------------
# Node.js (Angular)
# --------------------
[nodejs]
symbol = "󰎙 "
style = "green bold"
format = "[$symbol($version )]($style)"

# --------------------
# Command duration
# --------------------
[cmd_duration]
min_time = 500
format = "took [$duration]($style) "
style = "yellow"

# --------------------
# Prompt character
# --------------------
[character]
success_symbol = "[❯](green bold)"
error_symbol = "[❯](red bold)"
